"""Structural skeleton tests for examples/trace-jepa.

Mirrors tests/test_ijepa_cifar10_skeleton.py: validates the example's
file shape and key contract elements without actually running training
(which needs a GPU + the synthetic corpus generated by prepare.py).
Catches regressions like:

- accidental mutation of frozen prepare.py (loss of WebDataset shard
  schema, removal of canary.json output, removal of manifest.json)
- removal of required emit_progress / assert_no_grad_on_target calls
  from train.py (these would normally be enforced by the AST validator
  during a campaign — this test catches them at PR time)
- drift between program.md hard-rules wording and the JEPA_HARD_RULES
  prompt fragment
- config.yaml losing the Basilica target / probe_auroc objective /
  recalibrated forecaster defaults / Phase-3 codebook search axes /
  Phase-3 30-iter budget

The actual end-to-end smoke (`./run.sh smoke`) and the Basilica
campaign run are tracked in `TODO.md` Phase-3 — they require runtime
resources outside CI.
"""

from __future__ import annotations

from pathlib import Path

import yaml

EXAMPLE_DIR = Path(__file__).parent.parent / "examples" / "trace-jepa"


class TestExampleFilesPresent:
    def test_all_required_files_exist(self) -> None:
        for name in (
            "prepare.py",
            "train.py",
            "program.md",
            "config.yaml",
            "README.md",
            "run.sh",
            "requirements.txt",
            "deploy.py",
            "Dockerfile",
        ):
            path = EXAMPLE_DIR / name
            assert path.is_file(), f"missing required example file: {name}"

    def test_run_sh_is_executable(self) -> None:
        import os

        path = EXAMPLE_DIR / "run.sh"
        assert os.access(path, os.X_OK), "run.sh must be executable"

    def test_deploy_py_is_executable(self) -> None:
        import os

        path = EXAMPLE_DIR / "deploy.py"
        assert os.access(path, os.X_OK), "deploy.py must be executable"


class TestPrepareFrozen:
    """Frozen contract: prepare.py exposes exactly the documented surface."""

    def test_prepare_declares_main(self) -> None:
        src = (EXAMPLE_DIR / "prepare.py").read_text()
        assert "def main(" in src

    def test_prepare_writes_documented_outputs(self) -> None:
        src = (EXAMPLE_DIR / "prepare.py").read_text()
        for output_file in (
            "manifest.json",
            "canary.json",
            "shards",
        ):
            assert output_file in src, f"prepare.py must mention {output_file}"

    def test_prepare_carries_event_schema(self) -> None:
        src = (EXAMPLE_DIR / "prepare.py").read_text()
        for field in (
            "action_name",
            "action_type",
            "args",
            "return_code",
            "timestamp",
            "actor_id",
            "parent_link",
        ):
            assert field in src, f"prepare.py must carry event-schema field {field!r}"

    def test_prepare_emits_attack_overlays(self) -> None:
        src = (EXAMPLE_DIR / "prepare.py").read_text()
        # InjecAgent + AgentDojo overlays per writeup §11 Phase-3.
        assert "InjecAgent" in src or "INJECAGENT" in src
        assert "AgentDojo" in src or "AGENTDOJO" in src
        assert "is_attack" in src

    def test_prepare_supports_n_sessions_arg(self) -> None:
        """The 100K smoke / 1M production knob from writeup §11 Phase-3."""
        src = (EXAMPLE_DIR / "prepare.py").read_text()
        assert "--n-sessions" in src


class TestTrainContract:
    """Mutable but contract-bound: train.py must keep the AST validator's
    required calls."""

    def test_emit_progress_is_called(self) -> None:
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert "from autojepa.target.progress import emit_progress" in src
        assert "emit_progress(" in src
        assert '"probe_auroc"' in src

    def test_assert_no_grad_on_target_is_called(self) -> None:
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert "assert_no_grad_on_target" in src

    def test_canary_loss_is_emitted(self) -> None:
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert '"canary_loss"' in src

    def test_uses_future_block_mask(self) -> None:
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert "FutureBlockMask" in src
        assert "MultiBlockInfillMask" in src
        assert "CompositeMask" in src

    def test_codebook_bottleneck_is_present(self) -> None:
        """The MTS-JEPA Phase-3 design lever lives inside train.py per
        ADR-001 / TODO.md Phase-3 scope guard (NOT in core)."""
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert "SoftCodebookBottleneck" in src
        assert "codebook_size" in src
        assert "codebook_loss_weight" in src

    def test_codebook_is_NOT_in_core(self) -> None:
        """Scope guard: SoftCodebookBottleneck must not leak into
        src/autojepa/models/. Per ADR-001 the codebook is example-
        specific and putting it in core repeats the contrib-namespace
        mistake AutoJEPA explicitly rejected."""
        repo = Path(__file__).parent.parent
        models_dir = repo / "src" / "autojepa" / "models"
        for py in models_dir.glob("*.py"):
            assert "SoftCodebookBottleneck" not in py.read_text(encoding="utf-8"), (
                f"{py} leaked SoftCodebookBottleneck — should live only inside "
                "examples/trace-jepa/train.py per TODO.md Phase-3 scope guard"
            )

    def test_collapse_signals_emitted(self) -> None:
        src = (EXAMPLE_DIR / "train.py").read_text()
        # rankme + latent_var from autojepa.eval.collapse, lidar aliased
        assert "rankme" in src
        assert "latent_var" in src

    def test_outcome_json_is_written(self) -> None:
        """Mirror the Phase-2 outcome.json contract: status + metrics
        + elapsed_s + completed_steps + step_target."""
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert "outcome.json" in src
        assert "_write_outcome" in src

    def test_ar_params_json_contract(self) -> None:
        src = (EXAMPLE_DIR / "train.py").read_text()
        assert "AR_PARAMS_JSON" in src
        assert "AR_MODEL_DIR" in src


class TestProgramMdHardRules:
    """The example's program.md must encode the same JEPA invariants
    the global JEPA_HARD_RULES prompt fragment lists."""

    def test_lists_collapse_thresholds(self) -> None:
        src = (EXAMPLE_DIR / "program.md").read_text()
        for needle in (
            "latent_variance < 0.3",
            "effective_rank   < 32",
            "rankme           < 64",
            "lidar            < 80",
        ):
            assert needle in src, f"program.md missing collapse threshold {needle!r}"

    def test_lists_required_runtime_calls(self) -> None:
        src = (EXAMPLE_DIR / "program.md").read_text()
        assert "emit_progress(step, step_target, metrics={" in src
        assert "assert_no_grad_on_target" in src

    def test_states_phase3_falsifier(self) -> None:
        normalised = " ".join((EXAMPLE_DIR / "program.md").read_text().split()).lower()
        assert "phase-3" in normalised or "phase 3" in normalised
        assert "falsifier" in normalised or "kill criterion" in normalised

    def test_lists_three_baseline_soft_gate(self) -> None:
        """Per TODO.md Phase-3 Trace-JEPA-Evaluation belief: must compare
        against LogLLaMA + GraphIDS/SAFE + MTS-JEPA."""
        src = (EXAMPLE_DIR / "program.md").read_text()
        assert "LogLLaMA" in src
        assert "GraphIDS" in src or "SAFE" in src
        assert "MTS-JEPA" in src

    def test_lists_phase3_decision_gates(self) -> None:
        src = (EXAMPLE_DIR / "program.md").read_text()
        assert "phase3_falsifier" in src
        assert "baseline_separation" in src


class TestConfigYaml:
    def _config(self) -> dict:
        return yaml.safe_load((EXAMPLE_DIR / "config.yaml").read_text())

    def test_objective_is_probe_auroc_max(self) -> None:
        cfg = self._config()
        assert cfg["objective"]["metric"] == "probe_auroc"
        assert cfg["objective"]["direction"] == "max"

    def test_target_is_basilica(self) -> None:
        cfg = self._config()
        assert cfg["target"]["type"] == "basilica"

    def test_basilica_accepts_a100(self) -> None:
        cfg = self._config()
        assert "A100" in cfg["target"]["basilica"]["gpu_models"]

    def test_basilica_gpu_count_one(self) -> None:
        """Phase-3 single-GPU spec per writeup §11."""
        cfg = self._config()
        assert cfg["target"]["basilica"]["gpu_count"] == 1

    def test_policy_is_hybrid_with_jepa_widened_defaults(self) -> None:
        cfg = self._config()
        assert cfg["policy"]["type"] == "hybrid"
        assert cfg["policy"]["hybrid_param_explore_iters"] >= 25
        assert cfg["policy"]["hybrid_stall_threshold"] >= 5

    def test_intra_iteration_cancel_uses_ssl_defaults(self) -> None:
        cfg = self._config()
        ic = cfg["controller"]["intra_iteration_cancel"]
        assert ic["enabled"] is True
        assert ic["min_steps"] >= 2000
        assert ic["poll_interval_s"] >= 30.0
        assert ic["min_reports_before_decide"] >= 10

    def test_max_iterations_is_phase3_budget(self) -> None:
        """Writeup §11 Phase-3 calls for 30 iters > Phase-2's 20."""
        cfg = self._config()
        assert cfg["controller"]["max_iterations"] == 30

    def test_codebook_size_search_dim(self) -> None:
        """Phase-3 search axis per docs/research/mts-jepa.md and
        TODO.md Phase-3 codebook bottleneck section."""
        cfg = self._config()
        params = cfg["policy"]["params"]
        assert "codebook_size" in params
        assert 0 in params["codebook_size"]  # vanilla JEPA control
        for size in (64, 256, 1024):
            assert size in params["codebook_size"], (
                f"codebook_size={size} required by TODO.md Phase-3"
            )

    def test_codebook_loss_weight_search_dim(self) -> None:
        cfg = self._config()
        params = cfg["policy"]["params"]
        assert "codebook_loss_weight" in params
        for w in (0.0, 0.1, 0.5, 1.0):
            assert w in params["codebook_loss_weight"], (
                f"codebook_loss_weight={w} required by TODO.md Phase-3"
            )

    def test_future_block_mask_weight_in_search(self) -> None:
        cfg = self._config()
        params = cfg["policy"]["params"]
        assert "future_block_weight" in params
        assert "multi_block_weight" in params

    def test_standard_jepa_search_dims_present(self) -> None:
        cfg = self._config()
        params = cfg["policy"]["params"]
        for dim in (
            "learning_rate",
            "weight_decay",
            "batch_size",
            "max_steps",
            "predictor_depth",
            "num_targets",
            "ema_decay_start",
        ):
            assert dim in params, f"missing standard JEPA search dim: {dim}"
